---
# https://docs.docker.com/install/linux/docker-ce/fedora/

- name: Uninstall old versions
  yum:
    name: >-
        docker, docker-client, docker-client-latest,
        docker-common, docker-latest, docker-latest-logrotate,
        docker-logrotate, docker-selinux, docker-engine-selinux, docker-engine
    state: absent
  become: yes

- name: Setup yum repository
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    checksum: "sha256:3af973c1f2e16a032a11074eb22b440894ad4936c9ca86b666f8cf8342b7bea7"
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
  become: yes

- name: Install Docker-CE
  yum:
    name: docker-ce, docker-ce-cli, containerd.io
    state: present
  become: yes
